### ISSUE TITLE
[Question] How to export memory to the WASM module?

### ISSUE THREAD

**Issue by christopher-kleine** [tetratelabs/wazero#1059]
Hi,

I'm developing a Runtime for the [WASM-4](https://github.com/aduros/wasm4) Fantasy Console.  It's specification uses 64k of Memory.

In an earlier version, I was able export the memory using this code:
```go
builder := result.runtime.NewModuleBuilder("env")
result.env, err = builder.
	// Drawing
	ExportFunction("blit", result.Blit).
	// (Other exported functions)
	// Memory
	ExportMemoryWithMax("memory", 1, 1).
	Instantiate(result.ctx)
```
I used the version in Commit 5ed31d3c495d7eef7c82bdab9c0ec1c270eb72eb for this. 
Some time after that a PR arrived updating the code to v1.0.0-pre.3
I checked if the code compiled and was happy that it did.
However, any WASM4-file I try returns a "memory" is not exported in module "env".
I checked the examples and the exported functions. However I was unable to find a way to re-export the memory to the module.
I just tried if this changed with the current pre.7, but couldn't find any solution this.

Is it still possible to export memory to a named environment or do I have to go to the earlier version?
It's not urgent, since I only occasionally work on it and only today noticed there is a new PR updating it to pre.4.
The problem remains however.

Just in case: The project in question is [w4g](https://github.com/christopher-kleine/w4g).

**Comment by codefromthecrypt** [comment]
Hi, there. Typically, the compiler of the guest exports memory to the host, not visa versa, as that's what controls allocation functions and whatnot. So, there's something a bit different going on in w4g than normal. It is still possible to get what you are looking for accomplished, just needs a little indirection:

[ host module exports functions ] -> [ wasm env module re-exports those and exports memory] -> [ w4g imports env]

I'll try to spike something on your repo!

**Comment by codefromthecrypt** [comment]
https://github.com/christopher-kleine/w4g/pull/2 should handle this

**Comment by christopher-kleine** [comment]
Thanks for the clarification.  And for the PR that fixed pretty much all issues so far. Now it's up to me to actually fix the runtime.

**Comment by mathetake** [comment]
I believe this has been answered in https://github.com/tetratelabs/wazero/issues/1059#issuecomment-1402342596 with a workaround, and we believe that helps in most cases. Closing.

**Comment by boli2017** [comment]
> I believe this has been answered in [#1059 (comment)](https://github.com/tetratelabs/wazero/issues/1059#issuecomment-1402342596) with a workaround, and we believe that helps in most cases. Closing.

I'm sorry, is there any example?

**Comment by codefromthecrypt** [comment]
@boli2017 since this is an edge case, adding an example to our examples directory might be confusing (encouraging as practice which is a bit unusual). Instead, I'll walk through the workaround in practice, in w4g

1. define the exports you need including memory in text format, using wat2wasm to compile it. These will forward calls to a host module (e.g. with "go" prefix or something)
https://github.com/christopher-kleine/w4g/blob/ad3b2f4990497063c2aaffdc5c3370cc4e5b05f1/pkg/runtime/wasm/env.wat#L195

2. define the actual host functions in a host module, making sure it is what's imported above. instantiate that.
https://github.com/christopher-kleine/w4g/blob/0d1a7ac79fac96715ec9e512bbb8e5c69eaaf5fd/pkg/runtime/runtime.go#L93

3. embed and instantiate the module you compiled from text format (which includes forwarding functions and your exported memory)
https://github.com/christopher-kleine/w4g/blob/0d1a7ac79fac96715ec9e512bbb8e5c69eaaf5fd/pkg/runtime/runtime.go#L64
https://github.com/christopher-kleine/w4g/blob/0d1a7ac79fac96715ec9e512bbb8e5c69eaaf5fd/pkg/runtime/runtime.go#L174

hope this helps!
