### ISSUE TITLE
optimize module instantiation when there's no name

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1258]
Currently, our locks around module instantiation are name based. This protects the runtime from conflicts where one module can mask the exports of another. In #1244, we forbade importing extern types, such as functions, from modules without a name. We called that concept "anonymous modules".

What's left to do is safely optimize instantiation performance for anonymous modules. For example, a module without a name can use a cheaper lock than a string based one. It can use a numeric key such as from its pointer, or a lookup key, such as how we handle open file descriptors. This key would be used to ensure a runtime closes it, and also that if the module is closed explicitly, it is deregistered from the runtime. The last part is important to ensure that the "open modules" doesn't grow unbounded in scenarios where many modules are created.

### don't decouple anonymous modules from their runtime.

It is important that implementing this is done safely. For example, the defer `rt.Close(ctx)` convention works exactly as today, even if optimized underneath. Most compilers do not set a module name, and people are trained to trust runtime.Close. The runtime should remain the owner of its modules, regardless of their name.

A future feature of "forget" or "unsafe" module could be made to deregister a module so that closing a runtime never closes it. This requires careful use to avoid safety problems. In any case, this should be done *after* optimization of anonymous modules, so that the precise performance gains can be put in context of its cons.

### Notes

Here are some notes from @mathetake on the last attempt, in #1244

> one thing is that even anonymous modules should be captured by wasm.Store, so something like this https://github.com/tetratelabs/wazero/pull/1244/commits/bb57f1abaa57971213b426e04bc4952ae9c0fe6a should be required to create a set of anonymous modules

ref: https://gophers.slack.com/archives/C04CG4A2NKX/p1678974561121089?thread_ts=1678864254.795459&cid=C04CG4A2NKX

cc @achille-roussel  @Pryz @ckaznocha

**Comment by achille-roussel** [comment]
I've been doing some more thinking on the topic.

First, I think we have a good base to _enable_ multiple instantiation of anonymous modules in https://github.com/tetratelabs/wazero/pull/1259, we can potentially move forward with the PR tho it has limitations in terms of usability.

The main limitation is the way where wazero automatically inherits the module name from the wasm binary if none were specified by the application, see https://github.com/tetratelabs/wazero/blob/main/runtime.go#L285-L288 If the compiler injected a name into a wasm module, there is no mechanism by which we can remove that name and instantiate it multiple times.

I'm not going to cover the ability to _not register_ modules to the runtime, as it is a performance optimization that is decoupled from the feature of being able to instantiate anonymous modules. It is a related problem to keep in mind in API design but I don't think we need to solve these together.

To summarize the goals as I understand them:
- we need a mechanism to register unnamed module (https://github.com/tetratelabs/wazero/pull/1259)
- we need a mechanism to allow instantiating modules multiple times without giving them unique names (TBD)

I will lay out a few ideas, some we have discussed in parts before. Please let me know what you think!

## Do not inherit the module name by default

One way to allow instantiating multiple copies of a module would be to make all modules "anonymous by default", unless `WithName` is called with a non-empty name.

We discussed this option before, and I believe aligned on the idea that the _magic empty module name_ was coupling multiple behaviors under one property, with likely poor outcomes in the long term. The naming of a module should not determine whether it can be instantiated multiple times.

This approach has the upside of decoupling the behavior of wazero from the behavior of the compiler that originally created the module. The implicit relationship between the two can create issues that can be difficult to anticipate. Forcing the application to always declare its own module name could be a useful feature.

## Configure module instantiation to be anonymous

The idea would be to add a module configuration option which explicitly tells that the module can be instantiated multiple times, and therefore is registered in the runtime's anonymous module list instead of the map of module to name.

The configuration option could either be part of `ModuleConfig` (e.g. `WithAnon(bool)`), or it could be a separate instantiation method on `Runtime` like `InstantiateAnonymousModule`.

@codefromthecrypt suggested that it might be better to manage this at the runtime level.

## Configure the runtime to make module instantiation anonymous

Allowing instantiation of unnamed modules could be a property or state of the runtime. We cannot create a runtime that allows _only named_ or _only anonymous_ modules because resolving imports requires named modules. Instantiation of anonymous modules must always cohabit with the registration of named modules.

I have thought of two ways to express this:

### Sealing

_Sealing a runtime_ would be a mechanism through which the program could switch a `Runtime` to stop registrating modules by name and only register them as anonymous (even if they had a name). The program would call a `Seal()` method to declare the point after which all module instantiation becomes anonymous.

```go
// before sealing, modules are registered by name
err := rt.Seal(ctx)
// after sealing, all modules instantiated by rt are anonymous
```

### Forking

This alternative would be somewhat similar to the historical concept of _namespaces_ in wazero; I don't have a lot of background around why it was removed, but as a user I remember namespaces being difficult to reason about.

When forking a runtime, the application would create a new runtime which inherits all the registered modules but with the opportunity to modify some configuration parameters.

```go
fork, err := rt.Fork(ctx, wazero.NewRuntimeConfig().WithMultiModuleInstances(true))
// fork inherits all the modules of rt
// configured to allow multiple module instances so newly created modules will be anonymous
```

**Comment by codefromthecrypt** [comment]
It might take some digesting, but I think we maybe could make this part easier

> we need a mechanism to allow instantiating modules multiple times without giving them unique names (TBD)

the result of ModuleConfig.WithName("") could be used many times. just the thing is how it is currently implemented, you can't tell the difference between if no name was specified, or that it was explicitly cleared. I think that could be fixed internally and perhaps make time for more thinking about other things. A lot of folks have to set module config anyway, I mean, and maybe clearing the name is a "no harm" thing to permit especially for folks who don't depend on that info.

**Comment by codefromthecrypt** [comment]
raised https://github.com/tetratelabs/wazero/pull/1277 meanwhile as I noticed we had a bug. All the while I assumed WithName("") *just worked* but I forgot to test it. I think that makes this discussion a bit easier.

**Comment by achille-roussel** [comment]
So the `WithName("")` approach sounds like a version of "Configure module instantiation to be anonymous" 👍 

I'm going to rebase https://github.com/tetratelabs/wazero/pull/1259 and I think it should be good to go!

**Comment by codefromthecrypt** [comment]
@achille-roussel yep exactly, just it isn't special cased for a scope higher than module
