### ISSUE TITLE
List of languages

### ISSUE THREAD

**Issue by gedw99** [tetratelabs/wazero#1491]
https://wazero.io/languages/ Has the 4 main ones .

there are a plethora of languages getting wasi / wasm support and it’s a constantly evolving area and so very hard to concretely say if Wazero can work with language x , y etc 

I was hoping that a “not official supported” or “ best effort” list and links to what’s out there as examples could be done.

sort of like an awesome list but also perhaps a running doc for each language of what does and does not quite work and why.

Effort / technical debt and boiling the ocean:

the idea is best effort 

A markdown of them in the Wazero repo that links to them 

a markdown of what are the blockers. Hard to maintain I know 

a ci to remedy the hard to maintain point above. Some on the awesome list  will have ci in place. 

—-

It is intended to edge / push the effort forward by surfacing what is happening as per Language support and possibly reduce the not invented here syndrome.

devs can then see what is out there and align efforts.

Over time things will improve and the list of blockers per language can be updated 

perhaps a repo with examples that are in CI  will be appropriate as candidate languages reach a level of maturity .

**Comment by codefromthecrypt** [comment]
I don't expect us to track all languages, but there is a way to know what is most supported. If we test something in CI it is more supported. So, to know what's formally supported, it is what we test, listed [here](https://github.com/tetratelabs/wazero/actions/workflows/integration.yaml). Maybe we can put this on the website somewhere? Is that where you would look, or in the README. 

Besides that, we only have [allocation examples](https://github.com/tetratelabs/wazero/tree/main/examples/allocation) for a few, and these are here. Allocation is chosen because it is a common issue not necessarily handled the same, but typically affects FFI based usage.

Beyond this, we do have [built-in imports](https://github.com/tetratelabs/wazero/tree/main/imports), but with the exception of assemblyscript, they aren't usually language specific.

How languages deal with things like wasi are way beyond the scope of this project and apply far beyond what wazero does. There can be dozens of issues per language, so best to follow them on aspects like ABI support. We have tried and failed to track these before for tinygo, as it is too many issues per topic.

Finally, if the fact we have language hints on our website, if that's confusing we can move it to the "appendix" section, but I don't think we would remove them without more than one person asking. I don't have a lot of feedback that these cause more harm in way of confusion etc than good.

Hope this helps!

**Comment by codefromthecrypt** [comment]
Here's an idea of a path forward which reduces redundancy in our content, while helping focus on wazero support. To the point of this issue, it would add a matrix of tests we verify similar to how we have a matrix around platforms today.

Effectively, we concentrate anything support related into one and only one page, on the website. It is currently split between our README and the specifications page (for wasi). This support page would also have a copy of what we have in our test matrix, so people don't need to look at GitHub workflows.

Here's what the refactoring would generally include. If I get a few :thumbsup: on this, I can help!

1. Move Appendix/Specifications to a top-level page named "Support" and merge in content from the README about what we test. Remove the content in the README for a link to the new Support page, and setup a link from the old Appendix/Specifications to the Support page.

2. Add the missing content about the language SDKs test into the new "Support" page, and update that when we update our workflow to test more things. We should not mention Go wasip1 until at least 1.21 beta is out.

3. Rename Languages to Appendix and add a redirect link to avoid broken bookmarks. We need this because the languages pages are our most viewed content. Calling it Appendix is the better name anyway because it is contributed content and not support policy or even wazero specific.

How does this sound?

p.s. You may wonder if our language appendix is out-of-date because it doesn't include GOOS=wasip1. The reason is that it is neither final nor available generally. We can't recommend to people getting started to use gotip. Once at least the beta of 1.21 is out, we can replace our GOOS=js page with content around GOOS=wasip1.

**Comment by gedw99** [comment]
This sounds sound :)  thanks for considering this. 

So big +1 from me.

You said you wanted sone help I think ? I could do some markdown refactoring. Am a bit pushed with work stuff so might not be too in sync or on time with the changes though

**Comment by codefromthecrypt** [comment]
@gedw99 so how about this.. if you get time before I do, help welcome :) I have some things to finish up in various places esp as we have 1.2 coming around the bend (next week).

A quick win could be to add a matrix to the existing README near the other matrix about platform support, so basically do step 2. above but before the site refactoring.

**Comment by gedw99** [comment]
Ok can do. 
will have a looky next week and make a PR.

**Comment by gedw99** [comment]
Sorry @codefromthecrypt but life got in the way as I am moving countries and things .. 

If anyone else wants to work on this please go for it
