### ISSUE TITLE
Option to make the clock not advance while executing the WASM code

### ISSUE THREAD

**Issue by ItalyPaleAle** [tetratelabs/wazero#1494]
We embed wazero in Dapr to allow users to run WASM code as HTTP middleware or using an "output binding". In both these cases, we see WASM as a way to execute (small-ish) amounts of code directly within Dapr.

As discussed in Discord ([conversation link](https://discord.com/channels/778680217417809931/944326195078647828/1111342683756179566)), WASM code executed by wazero has full access to the system clock with highly-accurate precision.

This is a potential concern because it can allow executing timing (side-channel) attacks against the host process, in this case the "daprd" runtime. A skilled attacker could, with some effort, use this to obtain information about the host process.

A solution, which is also implemented by other runtimes, could be returning a "fixed" time for the entire duration of the execution of the WASM code.  For example, take this C code:

```c
#include <stdio.h>
#include <unistd.h>
#include <time.h>

int main ()
{
  for(;;) {
    printf ("%ld\n", time(NULL));
    sleep(1);
  }
  return 0;
}
```

Running it today would print the UNIX timestamp increasing by 1 second (approx) every time.

If the time were fixed, it would always print the same number.

This could be offered as an option for users that want to be more protected when running WASM code that is not fully trusted.

**Comment by codefromthecrypt** [comment]
Hi @ItalyPaleAle By default, wazero includes an advancing clock which doesn't use system time. When we first setup dapr, we decided to not use that and instead use the real time. If you remove these lines no system access will happen at all:

https://github.com/dapr/components-contrib/blob/master/bindings/wasm/output.go#L67-L69
https://github.com/dapr/components-contrib/blob/master/middleware/http/wasm/httpwasm.go#L54-L57

We have some notes about fake clocks, and why when you don't use system time, we advance it here https://github.com/tetratelabs/wazero/blob/main/RATIONALE.md#syswalltime-and-nanotime If advancing is required elsewhere besides Go, I'm not sure, but one risk of supplying a constant time is that not all code expects that.

In any case, the clocks are completely controllable in [ModuleConfig](https://pkg.go.dev/github.com/tetratelabs/wazero#ModuleConfig), and you can use either our default one or whatever you like. You can also decide to have an "unsafe" configuration that when set allows real time and real RNG vs a property to control each. This could allow end users to decide to use real time (as otherwise is surprising), without defaulting to it.

In any case, good question and I will close this and we can take any action you feel sensible on the components-contrib repo!
