### ISSUE TITLE
WASIX Support

### ISSUE THREAD

**Issue by moloch--** [tetratelabs/wazero#1495]
This is a longer term feature request, but would be great to have WASIX support in Wazero; 
* https://wasmer.io/posts/announcing-wasix
* https://wasix.org/

**Comment by ncruces** [comment]
The important bit to track is:
https://wasix.org/docs/api-reference#wasix-functions

The thread related stuff seems to depend on the [phase 3](https://github.com/WebAssembly/proposals/blob/main/README.md) [threads proposal](https://github.com/WebAssembly/threads) (which we deferred in #1487).

**Comment by codefromthecrypt** [comment]
@moloch-- so we currently have a table of supported functions in [wasi_snapshot_preview1](https://github.com/tetratelabs/wazero/blob/main/site/content/specs.md#webassembly-system-interface-wasi-wasi), so I imagine this would require a table for the extensions like [clock_time_set](https://wasix.org/docs/api-reference/wasix/clock_time_set).

I only just saw the docs today.. do you know what module name the extensions go into? Also, when we implemented WASI in the first place, we did things priority order instead of big bang. Can you mention which specific functions you need implemented and how you are using them (rust or c)?

**Comment by codefromthecrypt** [comment]
Also, there's recently a project that is more experimentation friendly https://github.com/stealthrocket/wasi-go One way to proceed is to develop the features there (as there's no back compat or windows requirements), then once stable we can add them here.

**Comment by ncruces** [comment]
> do you know what module name the extensions go into?

It's `wasix_32v1`, [apparently](https://github.com/wasmerio/wasmer/blob/554b20273aa71e25b28f6f6133740fb3d19bea1e/lib/wasi/src/utils/mod.rs#L131-L132).

**Comment by codefromthecrypt** [comment]
@moloch--  by the way, as wasix is a superset of wasip1, I expect its socket support to be "mix and match" capable. watch releases as I am writing notes about v1.2.0 which [adds experimental support for the socket functions](https://github.com/tetratelabs/wazero/pull/1493) defined in wasip1. There are glitches around non-blocking I/O, still, so if interested you can follow [this](https://github.com/tetratelabs/wazero/issues/1500#issuecomment-1574623676). It would be good to know which functions python uses, as I'm not currently sure if it uses the existing wasip1 ones or not..
