### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by it512** [tetratelabs/wazero#1663]
mikewang@VM-24-16-ubuntu:~/go_w/dd/cmd$ GOOS=wasip1 GOARCH=wasm ~/b/go/bin/go build server.go  
mikewang@VM-24-16-ubuntu:~/go_w/dd/cmd$ wazero run server
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
net.(*fakeNetFD).accept(...)
	/home/mikewang/b/go/src/net/net_fake.go:229
net.(*netFD).accept(0x14562c0)
	/home/mikewang/b/go/src/net/fd_wasip1.go:88 +0x3c
net.(*TCPListener).accept(0x142a0c0)
	/home/mikewang/b/go/src/net/tcpsock_posix.go:152 +0x4
net.(*TCPListener).Accept(0x142a0c0)
	/home/mikewang/b/go/src/net/tcpsock.go:315 +0x8
net/http.(*Server).Serve(0x1478000, {0xcb6e0, 0x142a0c0})
	/home/mikewang/b/go/src/net/http/server.go:3053 +0x2e
net/http.(*Server).ListenAndServe(0x1478000)
	/home/mikewang/b/go/src/net/http/server.go:2982 +0x10
net/http.ListenAndServe(...)
	/home/mikewang/b/go/src/net/http/server.go:3236
main.main()
	/home/mikewang/go_w/dd/cmd/server.go:15 +0xb

-------------------------
server.go
```golang

func main(){
    http.Handle("/foo", fooHandler)
    http.HandleFunc("/bar", func(w http.ResponseWriter, r *http.Request) {
        fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
    })
   log.Fatal(http.ListenAndServe(":8080", nil))
}
```
------------------------
**Environment (please complete the relevant information):**
- Go version: [e.g. 1.21.0]
- wazero Version: 1.5
- Host architecture: linux amd64

**Comment by evacchi** [comment]
I am not sure this is supposed to work the way you wrote it, but you are definitely not starting wazero with the --listen flag. Check the help for details

**Comment by achille-roussel** [comment]
Hello @it512 

The issue you are running into seem to be due to `GOOS=wasip1` not having complete network support. The WASI preview 1 specification did not contain a full definition of socket networking, so general features available on POSIX platforms such as opening listening sockets are not available.

This is unrelated to wazero and depends on the current implementation in Go, you will get a similar behavior if you try to run your program on another webassembly runtime.
