### ISSUE TITLE
Why does emscripten.Instantiate and InstantiateForModule differ drastically?

### ISSUE THREAD

**Issue by DejeroDaniel** [tetratelabs/wazero#1781]
One imports all the host functions needed, and the other barely imports anything. The documentation point you towards Instantiate, which won't work for any C++ module requiring exception support, for example.

Why don't they both set the same emscription host functions?

**Comment by ncruces** [comment]
Maybe @jerbob92 (the creator of [wazero-emscripten-embind](https://github.com/jerbob92/wazero-emscripten-embind) and our resident emscripten expert) can help?

**Comment by jerbob92** [comment]
That's because Emscripten dynamically registers host functions as needed, which are called invoke_xxx, where xxx is the function signature. Wazero needs to know the module so that it can generate the function as well (https://github.com/tetratelabs/wazero/blob/main/internal/emscripten/emscripten.go#L43). If Wazero wouldn't do this, it would need to register any combination possible, which is not feasible.

 I suspect `Instantiate` is left in to not break external code, but it's probably not very usable in most cases, so I would always go with`InstantiateForModule`.

Please note that real C++ exceptions is not supported by Wazero yet, I have been building that here:
https://github.com/jerbob92/wazero/blob/feature/implement-emscripten-cpp-exceptions/internal/emscripten/exceptions.go

And it does work, but I don't like the implementation so I'm still waiting for a response on https://github.com/tetratelabs/wazero/issues/1654 to make a PR.

**Comment by Danlock** [comment]
OK. Should I make a PR to change the documentation to use InstantiateForModule (since it sounds like Instantiate should be deprecated)?

**Comment by Danlock** [comment]
Also as an aside, I'm interested in using wazero to run Tesseract, compiled to WASM via Emscripten.
The Tesseract WASM emscripten imports are minimal enough that I'd figure I could try to implement them myself.  (env._emscripten_fs_load_embedded_files and env.system)

Do you think this project is feasible with the current support of emscripten in wazero?

**Comment by jerbob92** [comment]
> OK. Should I make a PR to change the documentation to use InstantiateForModule (since it sounds like Instantiate should be deprecated)?

Yeah, sounds good!

> Also as an aside, I'm interested in using wazero to run Tesseract, compiled to WASM via Emscripten. The Tesseract WASM emscripten imports are minimal enough that I'd figure I could try to implement them myself. (env._emscripten_fs_load_embedded_files and env.system)
> 
> Do you think this project is feasible with the current support of emscripten in wazero?

I don't know what these imports are, but generally you would need to recompile for a standalone WASM file, then you will have way less emscripten specific imports. I use this branch to compile my stuff so that it uses WASI for things like filesystem operations: https://github.com/emscripten-core/emscripten/pull/18285

So it is feasible, but you might need to do some special steps to get there.
