### ISSUE TITLE
Plans to support component model?

### ISSUE THREAD

**Issue by purplefox** [tetratelabs/wazero#2200]
Hi All,

Sorry for using an issue to ask a question, but didn't know how else to do this.

I started using wazero recently as a way to run custom functions in the database we are building. My experience so far is very positive!

Do you have plans to support component model, so we can have a standard, non custom way to pass complex types (strings, byte arrays etc) to and from wasm modules? Any timeline for this?

**Comment by evacchi** [comment]
We currently do not have sharable roadmaps in this regard.

**Comment by mathetake** [comment]
sorry the answer is definitely no until it is standardized in the w3c recommendation, which I don't think will happen in at least for the next 5 years or so.

**Comment by purplefox** [comment]
Thanks for your replies.

In the absence of component model support in the foreseeable future, do you have any other approach in mind for making it easier to support complex parameter types? For Rust/Go its not so bad as we can malloc/free in the module do unsafe casts to memory but this isn't possible in all languages that have WASM support, thus making them pretty much usable for use cases such as user defined functions running in a database (unless all params are int/float which is extremely restrictive)

**Comment by evacchi** [comment]
usually people provide a form of SDK and hide the serialization routines from the end users. Some approaches I have seen in the wild are based e.g. on protobuf (although generated code tends to be large) for instance see https://github.com/knqyf263/go-plugin or other serialization formats. If performance is not an issue I personally have used JSON because all languages have built-in support for it (especially on POCs)

Also, as a personal suggestion, you might want to checkout Extism, their Go runtime is based on wazero https://extism.org/docs/concepts/host-sdk

**Comment by nilslice** [comment]
@purplefox - if I may add another suggestion here, we recently added support to [Extism](https://github.com/extism/extism) (a universal wasm plugin system) for rich types using an open schema (similar to OpenAPI) called XTP Schema. You can read about it here: https://extism.org/blog/announcing-xtp-bindgen as well as its official docs at https://docs.xtp.dylibso.com/docs/concepts/xtp-schema

Using the [`xtp` CLI](https://docs.xtp.dylibso.com/docs/cli), It works much the same way as the WIT tooling for Component Model, except it will produce code to write Wasm modules which run in practically every wasm runtime. Feel free to join us on Discord or Slack to get more information if you are interested: https://docs.xtp.dylibso.com/docs/support/

For more information about it, how we support XTP, and the motivation behind it, you can also check out this recent post about our platform, however all XTP schema and code generators are free and open source: https://www.getxtp.com/blog/meet-xtp

**Comment by blaine-arcjet** [comment]
@purplefox The Component Model can actually be lowered or "transpiled" to Core Wasm, such as with [jco transpile](https://bytecodealliance.github.io/jco/transpiling.html). We, at [Arcjet](https://github.com/arcjet), have created a tool called [gravity](https://github.com/arcjet/gravity) that does this for Wazero since the Component Model is not on their roadmap.

**Comment by mpoindexter** [comment]
As @blaine-arcjet says, Component Model is actually built on top of Core Wasm, so there's not really a need for the Core Wasm system to know about Component Model. I've been working on an implementation of ComponentModel built on top of wazero: https://github.com/partite-ai/wacogo

It's pretty early, and WASI P2 support is quite barebones (just env/cli/stdio/stderr/stdout, read only FS and HTTP support for now), but I plan to continue to work on it.

It supports both zero code gen use of Component Model components (reflection style api), as well as generating stubs to implement host components in Go.
