### ISSUE TITLE
WASI Preview 2 support

### ISSUE THREAD

**Issue by nickchomey** [tetratelabs/wazero#2289]
**Is your feature request related to a problem? Please describe.**

A [recent announcement](https://wasmcloud.com/blog/compile-go-directly-to-webassembly-components-with-tinygo-and-wasi-p2) for using TinyGo with wasi preview 2 opened up a lot of possibilities. However, it can only work with a runtime that supports wasip2.

**Describe the solution you'd like**
It would be great if wazero could add support for wasip2

**Describe alternatives you've considered**

**Additional context**

**Comment by mathetake** [comment]
unfortunately, until WASI v1.0, I would recommend to use wasip1 because of the confusion and drama around WASI. 
In any case, you can implement any host environment by yourself including wasip2 if you want.

See #2200 as well where we clearly state that we will never support Component Model as well until it lands W3C recommendation which I believe never happen 😉

**Comment by mathetake** [comment]
ps I have never encountered a single person with a solid real world application who could elaborate on why they need them (esp. component model) and why the current WASI p1 doesn't fit for them. anyway nuff said, thank you for opening the issue as it's good to clarify our position publicly

**Comment by mathetake** [comment]
> if curious for a real world use case

i don't see any reason why it cannot be done without wasip2/component model. I am 99.99999% sure you won't need them

**Comment by blaine-arcjet** [comment]
@nickchomey The Component Model can actually be lowered or "transpiled" to Core Wasm, such as with [jco transpile](https://bytecodealliance.github.io/jco/transpiling.html). We, at [Arcjet](https://github.com/arcjet), have created a tool called [gravity](https://github.com/arcjet/gravity) that does this for Wazero since the Component Model is not on their roadmap.

**Comment by whitequark** [comment]
That's incredibly disappointing; I had high hopes for Wazero until encountering this issue. What "confusion and drama"? Why is a W3C recommendation remotely relevant here? The only drama I can see here is https://github.com/wazero/wazero/issues/2289#issuecomment-2232072988.
