### ISSUE TITLE
[question] High memory usage when used concurrently

### ISSUE THREAD

**Issue by cedric-cordenier** [tetratelabs/wazero#2308]
**Describe the bug**

I'm trying to follow the examples for concurrently instantiating modules, but am running into a) long instantiation times (1s+) and 2) high memory usage despite minimal instantiation and a toy WASM module. The example does not reliably run at less than 600 pages per instance.

I am new to WASM so may well be missing something obvious here :)

**To Reproduce**
https://github.com/cedric-cordenier/wazero-test

Go to the `wazero` and run `go run .`

The Go WASM module was compiled with `GOOS=wasip1 GOARCH=wasm go build -o ./testmodule.wasm ./main.go` from inside `wazero/module`.

This should log out an average duration of ~8s and activity monitor should show ~2gbs of memory used.

**Expected behavior**
I expected minimal memory usage and fast durations logged.

**Screenshots**

**Environment (please complete the relevant information):**
- Go version: 1.21.7
- wazero Version: v1.8
- Host architecture: arm
- Runtime mode: compiler

**Additional context**

**Comment by anuraaga** [comment]
Hi @cedric-cordenier - sorry for the late response. This seems to be an issue with the Go compiler. I found this comment

https://github.com/golang/go/issues/69018#issuecomment-2305964322

It seems as a rule +16MB is added to the initial memory of the module even if not needed, but it looks like they may improve this default.

When examining your wasm module with `wasm2wat`, we can see this reflected with a `(memory (;0;) 271)` setting the initial memory to 271 pages. It does make me wonder about the 600 pages number, if indeed something like 300 pages doesn't work. One note about your usage is it is creating a new `Runtime` every call, but we only want to create a module - we have an example here, the key point is using `WithName("")`. Following that example, you would also not need the compilation cache.

https://github.com/tetratelabs/wazero/blob/dbc4b62466477a7f3ac6537ce06ecfe66d7861fa/examples/concurrent-instantiation/main.go#L44

You'll probably still see large memory usage but there may be at least some improvement to be had by following that pattern. Anything left will likely also be on the Go compiler side rather than your code or wazero.

**Comment by ncruces** [comment]
If you have a specific work load in mind, you may also have better luck with a custom memory allocator.

wazero uses a `[]byte` and `append` for linear memory and it's up to the GC to allocate and free them. But a custom memory allocator can use a different strategy, and is notified of module closure (to free memory).

[This one](https://github.com/wasilibs/wazero-helpers/tree/main/allocator) uses `mmap`. Depending on usage patterns, one backed by a `sync.Pool` might be useful.

**Comment by cedric-cordenier** [comment]
Hi @anuraaga Thank you for taking a look! Let me incorporate the changes you suggested and see if that changes things.

**Comment by cedric-cordenier** [comment]
🤔 I've tried updating the example as per your recommendation @anuraaga and surprisingly things have actually gotten worse. I now measure 8 gigabytes of peak memory usage, rather than 2.

The profile suggests a lot of memory is taken up by MemoryInstance grow() so I wonder if any of the memory is being freed.

**Comment by mathetake** [comment]
> The profile suggests a lot of memory is taken up by MemoryInstance grow() so I wonder if any of the memory is being freed.

From this, i conclude that this is not the issue of wazero, but just the nature of the module used by you.
