### ISSUE TITLE
File operations do not defend against symlink traversal, permitting trivial escape from read-write mounts

### ISSUE THREAD

**Issue by neild** [tetratelabs/wazero#2321]
(I have been asked to report this bug via the public issue tracker.)

wazero does not appear to defend against symlink traversal in its filesystem APIs.

Since the WASI filesystem API permits creating symlinks, this allows for trivial access to the full filesystem from any program with a read-write mount. For example:

```
package main

import (
	"fmt"
	"io"
	"log"
	"os"
)

func main() {
	if err := os.Symlink("../../../../../../etc/passwd", "a"); err != nil {
		log.Fatal(err)
	}
	f, err := os.Open("a")
	if err != nil {
		log.Fatal(err)
	}
	b, _ := io.ReadAll(f)
	fmt.Println(string(b))
}
```

Run this program with read-write access to some directory:

```
wazero run -mount=restricted:/ main.wasm
```

It prints out the contents of /etc/passwd. /etc/passwd hasn't been exciting for a couple decades, admittedly, but this can be used to read or write any file anywhere on the filesystem that the account running wazero has access to.

**Comment by ncruces** [comment]
We need to decide if the issue is traversing the root at all, or if the issue is creating new symlinks that do.

What does WASI specify? Does it even specify this at all?

W.r.t. security, I don't speak for the team, but I'd like to say that I consider (1) sandboxing WASI a much (much!) harder effort than (2) sandboxing Wasm. And I feel that the level of effort that was put into (1) is lower than (2), both within wazero development, but also in terms of WASI and Wasm design to begin with.

So if you really care about security, yeah, you maybe shouldn't be using WASI *preview*.

**Comment by neild** [comment]
Note that simply preventing creating symlinks that traverse the root isn't going to suffice: An attacker can create a symlink that doesn't traverse the root (a/b/c/d/../../../etc/passwd), and then rename the containing directory (rename a/b/c/d => d).

Preventing creation of symlinks with any .. elements might suffice to prevent creating new escapes.

**Comment by ncruces** [comment]
Just leaving the code pointer here:
https://github.com/tetratelabs/wazero/blob/dc058c074d0bcce9b0e2da2619669d4ab443fb54/internal/sysfs/dirfs_supported.go#L36-L42

We can probably enforce some minimal rules here, like that running `path.Clean(link)` doesn't change `link`, and that `link` doesn't start with `../`.

It's likely that these checks should be inside `join`. I find the rational that `../` should for `path` be supported rather jarring:
https://github.com/tetratelabs/wazero/blob/dc058c074d0bcce9b0e2da2619669d4ab443fb54/internal/sysfs/dirfs.go#L87-L99

I mean: do we even need symlinks to evade the "root" at this point?

**Comment by evacchi** [comment]
if we do I think we might have to skip some wasi tests (but that might be ok)

**Comment by ncruces** [comment]
Would you mind testing b36a8c8952a230afaab2067672a1818f23c347e1, @neild, @evacchi?

I think all our current tests pass. This only allows creating symlinks that go down, not up (returns EFAULT otherwise, which seems [appropriate](https://man7.org/linux/man-pages/man2/symlink.2.html)).

**Comment by ncruces** [comment]
Having slept through this (not much admittedly), b36a8c8 has two issues with it.

`Symlink` must check that the cleaned path doesn't start with `/` either; also, it doesn't need to modify the path, I think. Leaving the path as is is fine, as long as the symlink always points down.

For `join`, we need to make a judgement call.

Lexically cleaning the path with `path.Clean` violates semantics: `/a/../b` is only the same as `/b` if `/a` exists and is a directory or a symlink to a directory.

Not lexically cleaning the path, however, is an issue if (e.g.) `/a` is a symlink to our root, because then `../b` evades the root.

BTW, unless I'm missing something, I don't think the `openat` family of calls protects against any of these issues. The only complete solution would be for our file system to implement [path resolution](https://www.man7.org/linux/man-pages/man7/path_resolution.7.html) all by itself.

**Comment by ncruces** [comment]
So, our options seem to be:
1. semantically wrong path resolution (`path.Clean`, b36a8c8952a230afaab2067672a1818f23c347e1 is a start)
2. root escapes in the presence of symlinks (even if we don't allow creating symlinks at all)
3. a bunch of syscalls on every file system access to do path resolution ourselves (`openat` family of syscalls may help here)

**Comment by ncruces** [comment]
In general the doc we should be reading about path resolution semantics we should be reading is:
https://github.com/WebAssembly/wasi-filesystem/blob/main/path-resolution.md#host-implementation

I hate it that I didn't find it sooner, but I hadn't worked on WASI filesystem directly myself before.

**Comment by tsmethurst** [comment]
Bit tangential perhaps but if you know ahead of time what your filenames will be, and what permissions you want to give your wasm application on them, you can implement quite a strict filesystem like this:

https://github.com/superseriousbusiness/gotosocial/blob/53ee6aef0885b4055ef95bf4f20ee78fd381e333/internal/media/util.go#L34-L77

And then give a config like this:

https://github.com/superseriousbusiness/gotosocial/blob/53ee6aef0885b4055ef95bf4f20ee78fd381e333/internal/media/ffmpeg.go#L242-L256

Or like this:

https://github.com/superseriousbusiness/gotosocial/blob/53ee6aef0885b4055ef95bf4f20ee78fd381e333/internal/media/ffmpeg.go#L158-L192

That's how we locked this down as much as possible in GtS anyway, though it may not apply for your use-case.

**Comment by ncruces** [comment]
Yep. I have this extreme example I used for a tool that reads from a single file (because it wants to seek, so doesn't like `stdin`, but is willing to output to `stdout`):
https://github.com/ncruces/RethinkRAW/blob/master/pkg/dcraw/fs.go

**Comment by ncruces** [comment]
As discussed above, this is working as specified in the [documentation](https://pkg.go.dev/github.com/tetratelabs/wazero#FSConfig).

I opened #2323 to track implementing path resolution, which would fix this.
