### ISSUE TITLE
Programs that succeed to execute with v1.6.0 sometimes hang indefinitely with v1.8.1 during instantiation.

### ISSUE THREAD

**Issue by davidmdm** [tetratelabs/wazero#2340]
**Describe the bug**
Programs that succeed to execute with v1.6.0 sometimes hang indefinitely with v1.8.1 during instantiation.
The same program crashes with v1.7.x

**To Reproduce**
Clone the example repository:
```bash
git clone https://github.com/davidmdm/wzbug.git
cd ./wzbug
./test.sh
```
**Expected behavior**
Program should behave the same as with the v1.6.0 runtime.

**Environment (please complete the relevant information):**
- Go version: 1.23.3
- wazero Version: v1.8.1
- Host architecture: Arm64 (M2 Mac)
- Runtime mode: Compiler

**Additional context**

Incredibly rare and difficult to reproduce. If I tweak the example program slightly, the bug disappears. If I don't use stdin the bug disappears. However I don't want to write programs fearing that the perfect storm will hang my execution.

**Comment by evacchi** [comment]
> If I don't use stdin the bug disappears. 
that's really useful, I wonder if that bug lies there entirely 🤔 stdin has a special treatment, especially in `poll_oneoff`

**Comment by mathetake** [comment]
relevant to 
https://github.com/tetratelabs/wazero/issues/2178  ?

**Comment by davidmdm** [comment]
@evacchi here is an incomplete things of weird things which have made the program succeed.

- using json.Unmarshal instead of K8s/yaml Decoder
- hard coding the data instead of parsing it from stdin
- parsing the data as is but removing any further code related to json encoding of the various k8 APIs 

However if I parse stdin using the yaml decoder from k8s and use that data it hangs.

**Comment by evacchi** [comment]
uhm, if you pipe into stdin then the fact it's stdin might be unrelated. In fact, you can try to run in interpreter mode and verify if that still occurs. If it does, then the problem might be WASI-related; otherwise it is likely to be an issue in the compiler. It would not be the first time Go's huge binaries make us spot an issue if you recall #2158 😬

**Comment by davidmdm** [comment]
@evacchi,

I just ran it using the interpreter and it ran successfully in all versions that I am testing: 1.6.0, 1.7.3, and 1.8.1.

Compiler it is?

**Comment by davidmdm** [comment]
I also pushed a new branch to the repository called `segfault`.

I modified the example program in what should be harmless ways... Just removing certain fields from the structs that I was going to json.Marshal, and this had the effect that both 1.6.0 and 1.7.3 worked as expected but 1.8.1 went from hanging to a segfault.

I am unsure what about my code is cursed, but hopefully it helps find the issue?

**Comment by evacchi** [comment]
most likely another issue with big binaries :D and possibly _again_ with jumps

**Comment by ncruces** [comment]
If it's a compiler issue, then testing `amd64` vs `arm64` is instructive. On a recent mac you can test both. On Linux you can do the same using Qemu and binfmt.

**Comment by evacchi** [comment]
ok first of all, I had to disable caching because it might have been masking the underlying issue. In my first bisect the offending commit seemed to be d4a49031b671b59fb832c95741df63b96f144104, and if I backed to 0b543f7ba4d00eb676fb719784f5de88d01aa573 the issue disappeared;

but really, if I disable the cache, it won't hang anymore, instead it panics:

```
❯ go run .
Using: github.com/tetratelabs/wazero v1.8.1
[debug] module compiled
[debug] instantiating module...
failed to execute wasm: failed to instantiate module: module closed with exit_code(2): stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x0 addr=0x0 pc=0x0]

goroutine 1 [running]:
bufio.(*Reader).ReadSlice(0x0, 0xa)
	/Users/evacchi/.local/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-arm64/src/bufio/bufio.go:351 +0x7
bufio.(*Reader).ReadLine(0x0)
	/Users/evacchi/.local/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.darwin-arm64/src/bufio/bufio.go:405 +0x2
k8s.io/apimachinery/pkg/util/yaml.(*LineReader).Read(0x1858000)
	/Users/evacchi/.local/go/pkg/mod/k8s.io/apimachinery@v0.31.2/pkg/util/yaml/decoder.go:362 +0x5

exit status 1
```

Notice that because I have `-edit replace`'d my local install it says v1.8.1, and thus the cache is _also_ reusing the same sub-directory all the time.

This time the bisect points to ab0d27c180a0d04a33060c3956299adfc07c3b75 and indeed if I back off to 48f702e154b5727bfb3ef734f7fe1f90631b3509 the bug goes away.

**Comment by evacchi** [comment]
specifically, the issue at https://github.com/tetratelabs/wazero/commit/ab0d27c180a0d04a33060c3956299adfc07c3b75 seems to be that it assumes that `_v.Valid()` is equivalent to being alive (`_, ok := aliveOnRegVRegs[v]; !ok`): 

https://github.com/tetratelabs/wazero/commit/ab0d27c180a0d04a33060c3956299adfc07c3b75#diff-8764afcaefa62bfdef6242059538727fb02013ea52e2a855e14f223230ed586bR996

**Comment by evacchi** [comment]
notice that if I run example.wasm through wasm-opt, the problem goes away

```
wasm-opt --enable-bulk-memory -Os example.wasm -o example.opt.wasm
```

which means that is likely related to the size

**Comment by davidmdm** [comment]
i've managed to use wazero v1.8.1 with wasm files that were closer to being ~70mb in size and it worked. My feeling is that its perhaps related but not simply a size threshold. 

I ended up reverting to v1.6.0 simply due to long compile times, but since I've managed to reduce my binaries down to 15mb I wanted to switch to v1.8.1 but here we are :)

**Comment by evacchi** [comment]
yeah, but it's not necessarily the _module_ size, but possible the size of the single _function_ :)

**Comment by evacchi** [comment]
to be more precise, this is the original

```
...
 - func[6470] size=28405 <k8s.io_apimachinery_pkg_apis_meta_v1.init>
 - func[3979] size=30582 <crypto_internal_nistec_fiat.p521FromMontgomery>
 - func[1664] size=42596 <unicode.map.init.1>
 - func[3976] size=48940 <crypto_internal_nistec_fiat.p521Square>
 - func[3975] size=48996 <crypto_internal_nistec_fiat.p521Mul>
 - func[7534] size=176411 <k8s.io_api_core_v1.init>
 ```
 
 this is the optimized binary 
 ```
 ....
 - func[6357] size=26875 <k8s.io_apimachinery_pkg_apis_meta_v1.init>
 - func[3911] size=27747 <crypto_internal_nistec_fiat.p521FromMontgomery>
 - func[1634] size=39647 <unicode.map.init.1>
 - func[3908] size=44336 <crypto_internal_nistec_fiat.p521Square>
 - func[3907] size=44390 <crypto_internal_nistec_fiat.p521Mul>
 - func[7375] size=167062 <k8s.io_api_core_v1.init>
 ```

**Comment by evacchi** [comment]
right, but now that I think again about it, if I start it with `GODEBUG=inittrace=1` evaluates that function successfully 😬

```
...
init golang.org/x/net/http2 @8.9 ms, 0.023 ms clock, 512 bytes, 9 allocs
init k8s.io/apimachinery/pkg/util/net @9.0 ms, 0.11 ms clock, 3032 bytes, 44 allocs
init k8s.io/apimachinery/pkg/runtime @9.1 ms, 0.066 ms clock, 624 bytes, 10 allocs
init k8s.io/apimachinery/pkg/apis/meta/v1 @9.2 ms, 1.6 ms clock, 46320 bytes, 360 allocs
init k8s.io/api/core/v1 @10 ms, 2.2 ms clock, 127056 bytes, 400 allocs
init k8s.io/api/apps/v1 @13 ms, 0.26 ms clock, 7904 bytes, 54 allocs
init k8s.io/api/rbac/v1 @13 ms, 0.12 ms clock, 4208 bytes, 32 allocs
init k8s.io/apiextensions-apiserver/pkg/apis/apiextensions @13 ms, 0.010 ms clock, 24 bytes, 2 allocs
init k8s.io/apimachinery/pkg/api/equality @13 ms, 0.015 ms clock, 400 bytes, 2 allocs
init k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1 @13 ms, 0.12 ms clock, 1504 bytes, 13 allocs
init github.com/yokecd/yoke/pkg/openapi @13 ms, 0.004 ms clock, 48 bytes, 1 allocs
```

hangs here 👆

**Comment by evacchi** [comment]
> specifically, the issue at [ab0d27c](https://github.com/tetratelabs/wazero/commit/ab0d27c180a0d04a33060c3956299adfc07c3b75) seems to be that it assumes that `_v.Valid()` is equivalent to being alive (`_, ok := aliveOnRegVRegs[v]; !ok`):
> 
> [ab0d27c#diff-8764afcaefa62bfdef6242059538727fb02013ea52e2a855e14f223230ed586bR996](https://github.com/tetratelabs/wazero/commit/ab0d27c180a0d04a33060c3956299adfc07c3b75#diff-8764afcaefa62bfdef6242059538727fb02013ea52e2a855e14f223230ed586bR996)

so revisiting this; the line is incorrect because `!ok` is **the opposite** of `!_v.Valid()`; i.e.:

```diff
-				if _, ok := aliveOnRegVRegs[v]; !ok {
+				if _v := blkSt.startRegs.get(r); !_v.Valid() {
```

should instead read:

```diff
+				if _v := blkSt.startRegs.get(r); _v.Valid() { // notice the missing negation
```

but I am trying to figure out where this condition has moved; presumably inside `reconcileEdge()` with 1fdaa0c737966e99191b3ab7ffe326713c536391 but this function has also lost the args:

```
	currentOccupants *regInUseSet,
	currentOccupantsRev map[VReg]RealReg,
```

so I wonder if it really is equivalent

**Comment by evacchi** [comment]
ok, regalloc might still be unrelated 😬 

I remembered I can inject function traces. 

	ctx = experimental.WithFunctionListenerFactory(ctx, logging.NewLoggingListenerFactory(os.Stdout))

This alters the compiled code, so the fun thing is that now even commit 48f702e hangs, and `main` won't hang anymore, but instead it crashes. 

The good thing is that at least I can get a function trace. The last function I get before the crash:

```
--> .sigs.k8s.io_yaml_goyaml_2ev2.yaml_parser_fetch_plain_scalar(0)
        --> .sigs.k8s.io_yaml_goyaml_2ev2.yaml_parser_save_simple_key(0)
```
and it returns from `yaml_parser_save_simple_key` so the crash should happen inside `yaml_parser_fetch_plain_scalar`

notice that between the call and the return, a whole bunch of things happen related to the GC. So this might be a memory-related issue. This is the full trace, https://gist.github.com/evacchi/179b1712b7b45c3f624f4a04fa018747 I have changed the trace so that the `<--` is followed by the function we're returning from.

**Comment by evacchi** [comment]
WELL WELL WELL WE MEET AGAIN #2158
Not 100% sure TBH 😅, but if I change the `maxUnconditionalBranchOffset` to e.g. `1<<26`; i.e. `(1<<24)*4` instead of `(1<<25 - 1)*4` I no longer get the issue, so I suspect it is still an integer overflow related to

https://github.com/tetratelabs/wazero/blob/d25ce10a01152b4c5f76c56b0c4a18ec5fa25cf1/internal/engine/wazevo/backend/isa/arm64/machine_relocation.go#L56-L58

**Comment by mathetake** [comment]
https://github.com/tetratelabs/wazero/blob/2c4b66bfbefa7fa21b26cb509f86a454a8b9c19c/internal/engine/wazevo/backend/isa/arm64/machine_relocation.go#L20

yeah this feels like a bug in my bit operation  lol

**Comment by mathetake** [comment]
can't believe we actually hit the corner case though - it sounds like almost miracle happening lol

**Comment by evacchi** [comment]
we'll buy you [a beer, 2 beers, 0 beers, -1 beers, a lizard, etc.](https://news.ycombinator.com/item?id=25851770)

**Comment by evacchi** [comment]
equivalently, it is also possible to tighten the `trampolineIslandInterval = maxUnconditionalBranchOffset / 2` to ` maxUnconditionalBranchOffset / 4`

**Comment by evacchi** [comment]
```diff
diff --git a/internal/engine/wazevo/engine.go b/internal/engine/wazevo/engine.go
index f02b905f..2dd180ad 100644
--- a/internal/engine/wazevo/engine.go
+++ b/internal/engine/wazevo/engine.go
@@ -283,7 +283,7 @@ func (e *engine) compileModule(ctx context.Context, module *wasm.Module, listene

                if needCallTrampoline {
                        // If the total size exceeds the trampoline interval, we need to add a trampoline island.
-                       if totalSize/trampolineInterval > len(callTrampolineIslandOffsets) {
+                       if totalSize/trampolineInterval >= len(callTrampolineIslandOffsets) {
                                callTrampolineIslandOffsets = append(callTrampolineIslandOffsets, totalSize)
                                totalSize += callTrampolineIslandSize
                        }
```

![](https://media.tenor.com/tI9cv0IJlpEAAAAM/rpx_syria-mic-drop.gif)

thanks @ncruces for the help brainstorming.

I think this is it, but I am too tired to verify @mathetake calling it a day 👋

**Comment by evacchi** [comment]
oh no some tests failed lol 🙈

**Comment by evacchi** [comment]
at this point the most promising approach seems to alter the `trampolineIslandInterval`; e.g.:

	// notice this is literally == maxSignedInt26 if that matters
	trampolineIslandInterval = (maxUnconditionalBranchOffset) / 4 

this will also pass all tests

now I am really giving up at least for today :D 👋

**Comment by evacchi** [comment]
update, only 1 island is created for the whole executable, but _no_ diff in the line:

```
		if diff < minUnconditionalBranchOffset || diff > maxUnconditionalBranchOffset {

```

makes the condition true. Which means that the following is true, thus, an island gets created

```
                       if totalSize/trampolineInterval > len(callTrampolineIslandOffsets) {
```

however no relocation uses it, so all jumps are relative and at least one of them is broken.

So why does this work if I set the condition above to >= (breaking something else) or if I make `trampolineIslandInterval` smaller?

My hunch: NOT because more islands are being used, but because in both cases 2 islands are being _INSERTED_ causing all offsets to shift just enough for some relative jump to fall within a valid range. 

- In the case with `>=` an island almost immediately (because `totalSize/trampolineInterval >= len(callTrampolineIslandOffsets)` means >=0, which when len==0 is true for any small `totalSize`), 
- in the case when `trampolineIslandInterval = (maxUnconditionalBranchOffset - 1) / 4` it's just creating twice as often because the interval is halved

In any case `diff < minUnconditionalBranchOffset || diff > maxUnconditionalBranchOffset` is NEVER entered, not even with the smaller `trampolineIslandInterval`

**Comment by evacchi** [comment]
```go
func encodeCallTrampolineIsland(refToBinaryOffset []int, islandOffset int, executable []byte) {
	for i := 0; i < len(refToBinaryOffset); i++ {
		trampolineOffset := islandOffset + trampolineCallSize*i
```

this function is given _all_ of the function offsets (`refToBinaryOffset`), len is 8404, i.e. 168_080 bytes, causing it to overwrite the start of the next function (which has been already written to `executable`). 

The issue is that `refToBinaryOffset` is indexed with the Wasm index, that includes all imported functions, thus the size is importedFn+localFn, while here it is only given the `localFns`

```
	trampolineInterval, callTrampolineIslandSize, err := machine.CallTrampolineIslandInfo(localFns)
```

if we fix the count in the loop above (in this case, we just `len(refToBinaryOffset)-27`, but any number >27 works, since it's not used anyway lol) then the bug is resolved.


> ![](https://camo.githubusercontent.com/ed042829bb67428b5a0065221307c39c2bed577e5d253112797948274a6d6a48/68747470733a2f2f6d656469612e74656e6f722e636f6d2f744939637630494a6c7045414141414d2f7270785f73797269612d6d69632d64726f702e676966) 

indeed, Bryan, indeed
