### ISSUE TITLE
How to distribute wasm with a Go module?

### ISSUE THREAD

**Issue by anderspitman** [tetratelabs/wazero#2348]
Is there a good way to distribute wasm payloads with Go modules which are intended to be used as libraries? Here's the ideas I've come up with:

* Create a separate repo just for the wasm. It can be cleared out occasionally (or maybe shallow cloned?) to keep the repo small
* Require devs to provide a wasm payload - worse dev experience. If they forget the app will refuse to run
* Download the wasm in the final application at runtime - devs/users might be surprised and/or upset by this behavior. Breaks if there's no internet connection
* Commit the wasm to the git repo and use `//go:embed` - would severely bloat repos

**Comment by anuraaga** [comment]
Hi @anderspitman - Just for reference, I maintain several libraries in https://github.com/wasilibs which are basically go repackagings of upstream codebases. The largest is probably [protobuf](https://github.com/wasilibs/go-protoc-gen-builtins), the most popular is [go-re2](https://github.com/wasilibs/go-re2) which more or less must `//go:embed` to provide the same API as `regexp`. Though in some sense these are similar to your first bullet though because the actual code development is in these upstream repos that just get built into Wasm in the wasilibs repos, so the churn in the `go-` repos is quite low - I'm comfortable using `//go:embed` because there just aren't that many commits needed to maintain them, and if it started getting bloated (go-protoc-gen-builtins has a 150M .git directory currently), shallow clones work. Another feature that helps is being OSS, so for end users goproxy will cache the contents and there won't be large git operations happening locally during `go get`.

I feel you've identified all the options and the tradeoffs for them, and then it's a matter of what suits the project the best, especially the amount of churn in either the development of the Wasm side vs the Go side. A combination of 2/3 doesn't seem too bad to me either where the bloat could be an issue - if your library has only one entry point that accepts a Wasm payload, devs can't forget to provide it, and you could also provide a helper that downloads it automatically, or the dev could choose to embed on their end.

**Comment by mathetake** [comment]
thanks rag!

**Comment by anderspitman** [comment]
Thank you @anuraaga! That's very helpful info and nice examples of one good way to do this.

`go get` doesn't use shallow clones right?

**Comment by inliquid** [comment]
Hi @anderspitman, if you are interested in storing Wasm artifacts and (for instance) retrieving them at runtime, I would suggest to look at OCI registry implementations, such as ORAS: https://oras.land/docs/client_libraries/overview

**Comment by ncruces** [comment]
> `go get` doesn't use shallow clones right?

`go get`, with most configurations, doesn't even use `git`, and yes it does do the equivalent to "shallow checkouts."
Read up on module proxies: https://proxy.golang.org/

**Comment by anderspitman** [comment]
> > `go get` doesn't use shallow clones right?
> 
> `go get`, with most configurations, doesn't even use `git`, and yes it does do the equivalent to "shallow checkouts." Read up on module proxies: https://proxy.golang.org/

That's helpful, thanks. So it looks like by default `go get` accessing the central proxy, which ingests VCS repos and then serves modules using the module proxy protocol?

I wonder is there any way to indicate to the central proxy that you don't want it to use VCS? [This](https://go.dev/ref/mod#serving-from-proxy) indicates that you can serve modules using your own proxy, but only in `direct` mode. I'm wondering if there's a way to do it transparently for consumers of the library.

That would let me host my wasm builds in a separate module that doesn't use VCS, and never need to worry about repo bloat.

**Comment by ncruces** [comment]
Possibly, but you'll probably need to use a vanity import, and setup a server that speaks the proxy protocol.

Also, don't forget your users may want previous versions. Repositories don't bloat _that_ much.

**Comment by anuraaga** [comment]
> Also, don't forget your users may want previous versions.

Glad to see general direction towards the simpler option, just one follow up on this just in case it was missed, don't forget that go.sum will prevent the contents of an import to be changed transparently, so there is basically no way of avoiding hosting multiple versions if going with an import scheme. Naturally, this doesn't apply to ad-hoc downloading at runtime.
