### ISSUE TITLE
Allowing host functions to return an error instead of panicing

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#258]
Right now, host functions that reach an abnormal end, or have to exit are required to panic out.

Ex. intentional return
```go
	panic(wasi.ExitCode(exitCode))
```

Ex. abend (ex on I/O)
```
		n, err := writer.Write(b)
		if err != nil {
			panic(err)
		}
```

This is an alternative to allowing signatures that return an error, then propagating out anyway. The reasons this isn't done yet are:

* Slight confusion about error because Wasm doesn't define them. We'd have to document the behaviour.
* Panic is easier internally as it is already used for global exits (exit from any recursive or reentrant calls)
* Less internal code (possibly more efficient to panic vs otherwise)

I believe this is confusing from a developer point-of-view, and can result in unnecessary error wrapping. An alternative may be to retain using panics internally for global exit, but use a different call site for functions with an error signature. These functions could internally panic on error to retain the same behavior.

**Comment by codefromthecrypt** [comment]
This is important for porting some existing gasm code, which return a second value which is an error. We need a clean path to migrate folks and saying "panic" looks like a step backwards.

**Comment by codefromthecrypt** [comment]
actually I looked closer at the code and it was returning an errno (uint32) cast as an error.  Let's start with #433 and also documenting what panics are used for now.

We have to analyze https://github.com/WebAssembly/exception-handling before proceeding with any typed errors I think

**Comment by codefromthecrypt** [comment]
hi @clarkmcc WebAssembly doesn't have a way in 1.0 or 2.0 to catch exceptions, though it may be the case in the [future](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md).

So, the way errors work are somewhat old school meanwhile. The first return val can be an errno for a recoverable function. This is how WASI works, for example. Please reply if you need more guidance!

**Comment by codefromthecrypt** [comment]
I think what you'll want to look at are..

* allocation (for the string and how to pass it, etc) https://github.com/tetratelabs/wazero/tree/main/examples/allocation/rust
* multiple values (how to return multiple things) https://github.com/tetratelabs/wazero/tree/main/examples/multiple-results

hope these breadcrumbs help!

**Comment by codefromthecrypt** [comment]
I don't think rust supports multiple values, so your signature might look like this. Note you probably don't need to declare a i64 for the errorno a smaller i32 is likely fine

```rust
pub type Size = usize;
pub type Errno = u16;

#[link(wasm_import_module = "your_module")]
extern "C" {
    fn get_value(ptr: *mut u8, len: Size) -> Errno;
}
```

ported from wasi
https://github.com/bolucat/Firefox/blob/f9a6a21c8748b6d79a238c0285d9d24aad991767/third_party/rust/wasi/src/lib_generated.rs

**Comment by clarkmcc** [comment]
@codefromthecrypt let me clarify, in the `get_value` function, the guest will call the host and pass in a pointer and a length to the input parameters, and the host function needs to pass a pointer and a length back to the guest which will contain the result. I'm able to do the first half, I'm not sure how to pass a pointer and length back to the guest if my return value is reserved for an error.

**Comment by clarkmcc** [comment]
In the long term, I'd like to switch to flatbuffers instead of serialized JSON strings which is what I'm doing now so that I can get by bearings first. Given that, I'm guessing the null-terminated string approach is not an option. 

Can you clarify what your second option would look like, I'm not sure that I follow completely. Last night I took a stab at this type of process
* Host function signature looks like `func(ptr uint32, len uint32, resultPtr uint32, resultLenPtr uint32) Errno`
* Guest calls host function and sets the value at `resultPtr` and `resultLenPtr` to 0, then passes a pointer to their memory locations to the host function.
* Host function does it's work, allocates sufficient memory for the result, and then copies the data.
* Host function then sets the value at the `resultPtr` address to the memory offset of the previously allocated result and sets the value at the `resultLenPtr` to the length of the result.
* Guest function reads the updated values at `resultPtr` and `resultLenPtr`.

It almost worked but there was some slight data corruption and then out-of-bounds errors when the strings were really long so I'm sure I did something wrong. Then I realized this seems like quite a bit of work for what I think is a pretty common use case (arbitrary input bytes and arbitrary output bytes). Am I overthinking this?
