### ISSUE TITLE
TinyGo binary keeps memory consumption growing causing execution time to slow down

### ISSUE THREAD

**Issue by efejjota** [tetratelabs/wazero#450]
I have been prototyping a desktop application which gets images generated inside a Wasm module and displays them:
https://github.com/efejjota/ebiten-wasm-graphics

I have tried to keep it simple in order to learn Wazero.
The application repeatedly [calls an exported `draw` function](https://github.com/efejjota/ebiten-wasm-graphics/blob/6b1a229c1694c8351da91ec833e40101346f2920/main.go#L36) defined in the Wasm module.
[The `draw` function generates an in-memory image of a circle with a random color](https://github.com/efejjota/ebiten-wasm-graphics/blob/main/wasm/draw.go#L23).
Using Wazero I [read the image bytes from linear-memory](https://github.com/efejjota/ebiten-wasm-graphics/blob/6b1a229c1694c8351da91ec833e40101346f2920/main.go#L58) and draw it on the screen.

I would expect every call to `draw` function to take an approximately similar amount of time and resources, but that doesn't seem to be the case.
Wazero seems to allocate more and more memory on every call without ever releasing or reusing any previously allocated memory.

This is preventing the application to draw the images at a more or less constant pace.
Instead, from time to time the application completely stops drawing any new circles for some seconds,
but immediately afterwards it starts drawing several circles in a very short amount of time.
The periods in which the application stops drawing any circles become more and more frequent and seem to take longer.

By profiling the application I noticed that the call to the exported `draw` method [is allocating more and  more space in the heap,
possibly copying any previous memory to a new location](https://github.com/tetratelabs/wazero/blob/fb0b311844e489a4ecbfc6ff0ddee0441a1d13dc/internal/wasm/memory.go#L152) with additional space on every run. This could explain why the application seems to be drawing in bursts.

**Comment by efejjota** [comment]
I have created a new branch in which I have removed Wazero leaving the remaining code identical.
The intention was to check whether the issue still persisted or not. But this version works as expected:
- New circles are drawn at a stable pace
- Resource consumption remains stable

https://github.com/efejjota/ebiten-wasm-graphics/pull/1

**Comment by mathetake** [comment]
Hi @efejjota, thank you for trying out wazero in such an unique use case! 

> By profiling the application I noticed that the call to the exported draw method [is allocating more and more space in the heap,](https://github.com/tetratelabs/wazero/blob/fb0b311844e489a4ecbfc6ff0ddee0441a1d13dc/internal/wasm/memory.go#L152)

This clearly shows that this is wazero is totally worked as expected because this means *your Wasm program* is leaking memory but not wazero. To clearly; that `MemoryInstance.Grow` function corresponds to `memory.grow` instruction in WebAssembly, and the `memory.grow` instruction is called whenever [the heap is not enough for allocation in TinyGo](https://github.com/tinygo-org/tinygo/blob/release/src/runtime/gc_conservative.go#L292).

That said, your Wasm program is leaking memory, but I'm not sure what is actually leaking memory (maybe some dependency in your library allocating memory, or compiling wasm via `-gc=none`, etc)?  

Thanks!

**Comment by codefromthecrypt** [comment]
one thing I might suggest since the concern is about memory, is moving the `buf = new(bytes.Buffer)` into the draw function. It is possible something about how tinygo tracks memory isn't working well with reset. The less shared state you have, the better as it reduces the amount of things that can leak.

another way you can troubleshoot is to mock out the use of the 'gg' library and return a constant image until the program structure is known to work without leaking. The less variables the better.

It is confusing, but when you are using tinygo, you aren't generating code similar to what `go build` would do. It is especially different when targeting wasm. It is especially tricky that there's no way to put a breakpoint inside code compiled to wasm. That's why you are only noticing the side effects of something calling "memory.grow", not what actually caused that.

Concretely, WebAssembly has no built-in functions, ex. no garbage collector or allocation function. This is all implemented in code generated by tinygo. Ex an allocation function would end up calling "memory.grow" as Takeshi mentioned. wazero has no control over that, so the only thing you can do is effect the code that generates wasm. In this case, possibly the go code you are compiling with or flags you pass to tinygo to compile it.

Hope this helps, and good luck!

http://gophers.slack.com/ #tinygo channel may be a good one to go next.

**Comment by codefromthecrypt** [comment]
this fixed it btw, though trace logging is coming around soon thanks to @anuraaga https://github.com/efejjota/ebiten-wasm-graphics/pull/2
