### ISSUE TITLE
data count section not supported as feature "bulk-memory-operations" is disabled

### ISSUE THREAD

**Issue by inkeliz** [tetratelabs/wazero#516]
I'm using `WithFinishedFeatures()`:

	rConfig := wazero.NewRuntimeConfigJIT()
	rConfig.WithFinishedFeatures()

	runtime := wazero.NewRuntimeWithConfig(rConfig)
	if _, err := wasi.InstantiateSnapshotPreview1(context.Background(), runtime); err != nil {
		b.Error(err)
	}

	config := &wazero.ModuleConfig{}
	config.WithStdout(os.Stdout)

	wasifile, err := os.ReadFile(filepath.Join("testdata", "wasi", FileWasm))
	if err != nil {
		b.Error(err)
	}

	wasm, err := runtime.CompileModule(context.Background(), wasifile)
	if err != nil {
		b.Error(err)
	}

That is failing:

```
main_wasi_test.go:94: data count section not supported as feature "bulk-memory-operations" is disabled
```

In that case, the line is:  

	wasm, err := runtime.CompileModule(context.Background(), wasifile)
	if err != nil {
		b.Error(err)
	}

**Comment by inkeliz** [comment]
I need to use it like:

```
wazero.NewRuntimeConfigJIT().WithFinishedFeatures()
```

So `wazero.NewRuntimeConfigJIT()` returns an pointer, and also `WithFinishedFeatures()` takes an pointer, but doesn't modify the existent struct, instead it clone the existent one and return. I don't think it makes sense, since it's an pointer.

**Comment by codefromthecrypt** [comment]
Sorry about the confusion. Incidentally, I just recently changed the godoc on that to clarify it is immutable (and the other config isn't).

We are currently using only pointer receivers on our types as the reverse causes more problems. Basically review becomes more mechanical except a couple special cases, and also linters don't yell as much etc. It is true if someone was looking at the implementation of it being a pointer, this is confusing.

XXXConfig aren't quite "final" in their shape. An interface may be an outcome of this and the internal code wouldn't change (as a RuntimeConfig backed by runtimeConfig struct would likely still be implemented internally with pointers.)

Thanks for raising the mental glitch, I'm not sure what outcome we'll take at this moment, but appreciate the feedback, and it helps regardless. In any case, sorry for the glitch as it caused you distraction and that's not desirable for anyone.

**Comment by codefromthecrypt** [comment]
PS that ModuleConfig is mutable and RuntimeConfig is not is a bug in the former. I noticed it last weekend, but ran out of steam and ironically was going to fix that today.

```
// TODO: This is accidentally mutable. A follow-up PR should change it to be immutable as that's how baseline
// configuration can be used safely in modules instantiated on different goroutines.
type ModuleConfig struct {
```

**Comment by codefromthecrypt** [comment]
Thanks for the nudge. We are hoping to finish the API in the next couple weeks to put it in more a beta state. There are a few types like this we hadn't made interfaces for, yet. Here's the PR direct to the concern and note it also gets rid of the temporary "FinishedFeatures" thing as the W3C working group formalized a draft https://github.com/tetratelabs/wazero/pull/518

**Comment by codefromthecrypt** [comment]
ps to close on this, you were totally right. the design was sloppy and the intent was implicit and not knowable for people using this. While there are other ways out we discussed and decided that the most important aspect we want to relay with the API is that the internal state is important, but not something we want end users to deal with. To do that, we both don't export the fields (done before), and don't export the structs either (done now). Using interfaces will give us the ability to grant a more stable API to users while sacrificing a little control they might have if they were structs instead. That said, as fields weren't exported there was already limits to how much control one would have. At the end of the day, interfaces are a more honest representation of the API.

**Comment by inkeliz** [comment]
Maybe we can use some `Option Pattern`. Something similar to:

```
type RuntimeConfig struct {
	config runtimeConfig
}

type runtimeConfig struct {
	enabledFeatures     wasm.Features
	newEngine           func(wasm.Features) wasm.Engine
	memoryLimitPages    uint32
	memoryCapacityPages func(minPages uint32, maxPages *uint32) uint32
}

func NewRuntimeConfigJIT(opts ...RuntimeOptions) *RuntimeConfig {
	ret := engineLessConfig.clone()
	ret.config.newEngine = jit.NewEngine

	for _, opt := range opts {
		opt(&ret.config)
	}
	return ret
}

type RuntimeOptions func(c *runtimeConfig)

func OptionFinishedFeatures() RuntimeOptions {
	return func(c *runtimeConfig) {
		c.enabledFeatures = wasm.FeaturesFinished
	}
}

func OptionMemoryCapacityPages(maxCapacityPages func(minPages uint32, maxPages *uint32) uint32) RuntimeOptions {
	return func(c *runtimeConfig) {
		c.memoryCapacityPages = maxCapacityPages
	}
}
```

In that case, the RuntimeConfig is public, but the `config` isn't, so it can be changed. In order to set each option you must provide it during the initialization. So, you can use:

```config := NewRuntimeConfigJIT(OptionFinishedFeatures(), OptionMemoryCapacityPages(f))```

There's no real difference, the only change is that each `Option` can't be used outside of `NewRuntime*`, which prevents something it did.

**Comment by codefromthecrypt** [comment]
Thanks for the background. In the option pattern, it is true that you can allow arbitrary functions to apply configuration, and you can even control which are allowed by hiding the type it can apply to. It is totally possible to use independent functions instead of using functions attached to the thing it is affecting (ex via an interface or a struct).

There are a few things that get hairy, first to notice is when we start pulling apart config structs or interfaces into bare functions, we lose the namespace given to us by the config type.

Ex. RuntimeConfig.WithWasmCore2 -> RuntimeConfig and also OptionWasmCore2? not really as it is in the same package as other Config.. so do we start doing RuntimeConfigOptionWasmCore2? or do we now have to start breaking out more packages? Linking options back to the RuntimeConfig is less direct than normal godocs which are naturally attached to the struct or interface they are on. To redo the good parts of functions attached to a struct or interface on options is namespacing and linking work, and any time people have to manually namespace things like prefixing vs using an enclosing type, there's more chance of little typos etc. this increase the busywork imho.

Another concern maybe less obvious with RuntimeConfig is derived config. Based on user feedback, ModuleConfig was designed to allow overriding the env or args per call to InstantiateModule. For example, this lets you change the WASI args or env per call while holding other config constant. To accomplish this with options we would have to create another function to allow the same. Ex. instead of ModuleConfig.WithName("xx") to make a derived config, ModuleConfig.WithMoreOptions(ModuleConfigNameOption("xx")) or something.. It feels a step back.

Before, we used the Option pattern in WASI, but it got in the way. For example, if you don't define anything except options to affect something, you need to also shoehorn the option pattern to apply test config. This results in some odd looking anonymous functions that are less straight forward than fields or functions attached to the real object. Maintenance especially in WASI is a chore, and it has been less annoying since we undid that.

The context here is even more obscure than how we had used options in WASI as in WASI it was to build WASI, not to build the config to build WASI..

I guess what I'm trying to relate is not that options can't be used especially by folks who really want to use them. There are a fair number of go projects that do this. OTOH it isn't a required or universal practice in Go to use the option pattern, and I'm not sure all people would use it regardless of what it is applying to. I would suspect it is a particularly grey area to have both option and config pattern at the same time. I hope I've relayed in a way that you feel understood even if we may not agree.

Personally I don't want to redo all the types again just to make them use the option pattern. I don't think it would be less code for the end user and certainly it would be more for us to maintain, and we'd still have function-based stuff in the modulebuilder. That said, in a different context in a different project I might do it :D

**Comment by codefromthecrypt** [comment]
copied some of this and the surrounding context into RATIONALE.md so no one needs to read minds or issues to guess on it. Now shifting mind back to wasm stuff :P https://github.com/tetratelabs/wazero/pull/521
