### ISSUE TITLE
Assign the file system when calling function

### ISSUE THREAD

**Issue by knqyf263** [tetratelabs/wazero#563]
I'd like to pass the different filesystem when calling a function as below.

```
	callback := mod.ExportedFunction("callback")
	filepath.WalkDir("root", func(path string, d fs.DirEntry, err error) error {
		if d.IsDir() && (path == "appA" || path == "appB") {
			callback.Call(ctx, wazero.WithFS(os.DirFS(path)))
		}
		return nil
	})
```

This is because we want wasm to be able to access only files under `appA` and `appB`. As far as I know, it is not supported now. It would be like the following in wazero.

```
	code, err := r.CompileModule(ctx, wasmCode, wazero.NewCompileConfig())
	if err != nil {...}

	filepath.WalkDir("root", func(path string, d fs.DirEntry, err error) error {
		if d.IsDir() && (path == "appA" || path == "appB") {
			rooted := os.DirFS(path)
			config := wazero.NewModuleConfig().WithFS(rooted)
			mod, err := r.InstantiateModule(ctx, code, config)
			if err != nil {...}
			defer mod.Close(ctx)

			callback := mod.ExportedFunction("callback")
			callback.Call(ctx)
		}
		return nil
	})
```

Is this the best way? I am afraid of the penalty of initializing the module every time since it is called frequently.

**Comment by mathetake** [comment]
oh yeah, this sounds reasonable to me and should be possible. Assigning @codefromthecrypt as this is an API-related thing!

**Comment by codefromthecrypt** [comment]
@knqyf263 would context-based configuration work for you? This feels like the solution here, or at least a workaround. Something like https://pkg.go.dev/github.com/tetratelabs/wazero/experimental#Sys

**Comment by knqyf263** [comment]
Do you mean you will add a new function to the `Sys` interface?

**Comment by codefromthecrypt** [comment]
I was thinking another key, actually experimental.FSKey *

What would happen is that any call in the stack would have this as its FS, unless overridden again. Ex. wasm would see this FS, so would any host function call, recursively, unless some host function overrode the key again.

```golang
fn.Call(context.WithValue(ctx, experimental.FSKey{}, os.DirFS(path)), ....)
```

* We will clean up the "experimental" namespace after implementing WASI snapshot 2 #263 and/or adding the new FS type #390. I think doing too much now would probably end up drifting later due to these anyway, so experimental is likely not the worst way to describe it and meanwhile we can this out to you and figure out how well it works.

**Comment by codefromthecrypt** [comment]
oh.. (sorry jet lag) @knqyf263 are you also asking to have host functions read the FS? Maybe you can clarify what you need from this below:

1. have host functions read the current FS (currently only wasm can)
2. override the current FS for downstream calls (currently only via module instantiation)

* note we have both root and working directory FS at the moment

**Comment by codefromthecrypt** [comment]
ps overriding the FS entirely (similar to how it would be done in moduleconfig) is probably easier impl, though we'd have to add a security disclaimer anyway (as some WASI marketing says things like pre-open eg your code can't change the file policy after instantiation).

Another way is to allow a filter, which would be easier. Ex, if downstream are a subset of the initial files, that's safer to write.


Impl notes: internals are a bit awkward to re-expose as an FS due to how they are deconstructed during initialization, and that files can be currently open by the time you get to a host function call. This will get a little more interesting when we support an interface that can open files.  https://github.com/tetratelabs/wazero/blob/ab25a84b4f4894384a78fc92560ae96dedd96122/internal/integration_test/fs/fs_test.go

**Comment by knqyf263** [comment]
> oh.. (sorry jet lag) @knqyf263 are you also asking to have host functions read the FS? Maybe you can clarify what you need from this below:
> 
> 1. have host functions read the current FS (currently only wasm can)
> 2. override the current FS for downstream calls (currently only via module instantiation)
> 
> * note we have both root and working directory FS at the moment

I just need only #2 for now.

**Comment by codefromthecrypt** [comment]
ok I will make an experimental FSKey (not WorkDirFSKey), and refer to the godoc on ModuleConfig.WithFS

This will shadow any existing open files and whatnot.. I suspect we'll need to return a Close function of sorts, so that it can be cleaned up after the function call (similar to how a CancelContext works)

**Comment by codefromthecrypt** [comment]
well it might not be me personally, I might try to talk @anuraaga into doing this as I'm readying a talk for Gluecon :D

**Comment by knqyf263** [comment]
If you are busy, I can work on it if you guide me.

**Comment by knqyf263** [comment]
After taking a quick look, I guess this `fs.FS` should be replaced with the new `fs.FS` passed through context.Context.
https://github.com/tetratelabs/wazero/blob/b50bb931311ef5251155c1ea40b8125285fa9a59/wasi/wasi.go#L1220

And I'm considering how we should populate `openedFiles`.

**Comment by knqyf263** [comment]
@codefromthecrypt I opened a draft PR. I will add tests, but before that, I want to make sure I'm in the right direction. Could you take a quick look when you have time?

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/922 will remove this feature because it was only used once. @mathetake found another way to do it here https://github.com/aquasecurity/trivy/pull/3299
