### ISSUE TITLE
Declaring exports functions on the runtime causes friction

### ISSUE THREAD

**Issue by prep** [tetratelabs/wazero#599]
**Is your feature request related to a problem? Please describe.**
`wazero` has us declare functions on the runtime via `NewModuleBuilder().ExportXXX()`. This is fine for functions that can operate in a vacuum who don't need to know about the instance from which the call is happening. For functions that do need that type of context, this approach is limiting.

**Describe the solution you'd like**
`wasmer` sets these functions up during instance creation and `wasmtime` does more or less the same by setting them up in the linker from which the instance is derived. 

I am not familiar with the inner workings of `wazero`. Reasoning purely from a API point of view, I'd love to be able to specify these functions when calling `InstantiateModule()`.

**Describe alternatives you've considered**
Of course, the workaround here is to create an runtime per instance. However, this takes away any benefit from the result of `CompileModule()` whose purpose is to speed up instance creation using `InstantiateModule()`.

**Comment by codefromthecrypt** [comment]
Thanks for the description. If I understand correctly, this isn't so much about "Export" as wherever you do that, exported functions are how you accomplish an import binding.

It seems like you want the function binding to be a part of CompileModule. Ex to be able to supply a function import during wasm compilation. My guess is that doing so allows you to couple imports only used for one module. Is this right?

Keep in mind we won't likely achieve this the same way as the [deprecated linking proposal](https://github.com/WebAssembly/proposals/blob/main/inactive-proposals.md). Even if that still exists in wasmer, I think [wasmtime already deleted that](https://github.com/bytecodealliance/wasmtime-go/pull/125). However, we're interested in getting your problem solved.

As you may already notice, we have means in CompileConfig to rename imports so doing something like what you are saying seems reasonable (even if we may have tricks internally to make it work).

Main thing I want to know is if I understand you correctly, if you can mention concretely what you are doing (ex which type of imports you are satisfying.. wasi or custom ones), and what context you are using to decide exports, or if this is mainly just wanting to couple import function binding to compile module (for convenience)

**Comment by codefromthecrypt** [comment]
Finally, I'm assuming this is best to do in [CompileConfig](https://pkg.go.dev/github.com/tetratelabs/wazero#CompileConfig) similar to how we plug in [ImportRenamer](https://pkg.go.dev/github.com/tetratelabs/wazero@v0.0.0-20220528010030-f1467e545350/api#ImportRenamer). 

Just I don't know if you really need this to be deferred to instantiate or not.. If you did, it would be something based on the realized module name. This is why a small demo or code example helps, even if it is in wasmer at first.

**Comment by codefromthecrypt** [comment]
hi @prep I eventually figured out I think what is going on here. I looked at your https://github.com/prep/wasmexec repo and basically what I can tell is that you need a stateful "go" host module per wasm-defined one.

While we have host function parameters for context and api.Module (including access to memory), we don't have a way to attach arbitrary state per module. Due to this, if you need state per module, you'd need some means of looking it up (ex externref) or be able to bind an imported module multiple times. Right now, the only way to bind a module name multiple times is via a new runtime, and this undoes the compilation cache.

We could solve this problem by allowing a module to have an attachment map, but when I looked at your code, it isn't using the `api.Module` parameters anyway. So, anything we put on api.Module would require refactoring, and probably won't be compatible with your goal of making one framework for all wasm go libraries.

The other way is to extract the module namespace component so that runtime can create new namespaces instead of everything being a part of one flat one. Ex a namespace could be made, then you can instantiate a pair of modules into it, and those names won't conflict with any others in the runtime. I like this better than creating a new Linker concept, especially as we should save the new verbs and nouns for any future work on the component proposal. We already use the term namespace internally (what you instantiate modules into). I'll raise a PR on this.

**Comment by prep** [comment]
Hey @codefromthecrypt, thanks for responding and making quick work of it in a draft 👍  I'm a bit pressed for time so I haven't be able to look at your PR, but I will as soon as I find the time 😅

**Comment by codefromthecrypt** [comment]
@prep no worries on that. I meant it as an FYI

**Comment by codefromthecrypt** [comment]
ok I think https://github.com/tetratelabs/wazero/pull/604 is ready, and the description (and example) should show how to use it

**Comment by prep** [comment]
I've finally come around to testing this for my own use-case and it's perfect 👍 Thanks amigo!
