### ISSUE TITLE
Add compiler support for FreeBSD

### ISSUE THREAD

**Issue by knqyf263** [tetratelabs/wazero#607]
I tried to compile wazero for FreeBSD, but got an error.

```
../../../../pkg/mod/github.com/tetratelabs/wazero@v0.0.0-20220529032218-029a79476b4f/internal/engine/compiler/mmap.go:74:16: undefined: syscall.Mprotect
```

Looks like `Mprotect` is not implemented in `syscall`.
https://github.com/golang/go/blob/aac1d3a1b12a290805ca35ff268738fb334b1ca4/src/syscall/zsyscall_freebsd_amd64.go

It is implemented in `golang.org/x/sys/unix`. I confirmed I could compile it after replacing `syscall` with `golang.org/x/sys/unix`.
https://github.com/golang/sys/blob/bc2c85ada10aa9b6aa9607e9ac9ad0761b95cf1d/unix/zsyscall_freebsd_amd64.go#L296-L308

If wazero needs to keep zero dependency (otherwise, need to rename it to `waone`?), can't we even use `golang.org/x`? Do you want to re-implement syscalls for other platforms in wazero?

**Comment by codefromthecrypt** [comment]
hi @knqyf263 and thanks for reporting. yes it is indeed the goal to have zero deps. I think what you are hitting is lack of precision in our engine detection. It doesn't switch on a variant of linux so you are getting a later error like this (for the compiler). I suspect the interpreter would work, for example.

We have already added code for mmap for windows, based on demand, and ensure it with a test dimension. That allowed it to use the compiler instead of the interpreter, which doesn't have this issue.

We could add a runtimeconfig for BYOMMap easily enough so that folks can opt-into that for mmap. However, it may not be the only issue in the compiler. Our assembler has some platform specific nuance in it also. Let's first see what's going on in FreeBSD and get a test dimension up?

**Comment by codefromthecrypt** [comment]
I'll clarify something we'll have to put into docs somehow.

The compiler has components that aren't OS-specific (the assembler) and also parts that are: the engine impl has a little and also the mmap function.

Since FreeBSD had an issue with one of these parts, we should have a test dimension to ensure it works. This doesn't mean we can all operating systems, but in this case it sounds like we should as it hit an issue and you need it and it probably won't be hard to support!

**Comment by knqyf263** [comment]
> It doesn't switch on a variant of linux so you are getting a later error like this (for the compiler). I suspect the interpreter would work, for example.

I got it. So, another workaronud is wazero disables compiler for unsupported platform? Only interpreter will be available for some platform. It can be slower, but it is fine. If it is not hard to support mmap in other platforms, it is better though.

**Comment by codefromthecrypt** [comment]
indeed I think that we accidentally use compiler where we haven't tested it is a sort of bug. The intent was to fallback to interpreter when not supported. I'll narrow the flags down as the experience is better slow vs crash.

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/612 to make sure no-one else gets this error. After I'll work on FreeBSD

**Comment by codefromthecrypt** [comment]
haven't forgotten this. I will merge it while takeshi is afk next week :D

**Comment by codefromthecrypt** [comment]
testing is very slow, but this works. However, I have no means to test freebsd+arm64 https://github.com/tetratelabs/wazero/pull/671

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/671 has a glitch which is I can't recreate the failure locally. Also the test setup is brittle as vagrant rate-limits us. I'm tempted to use travis to verify if there's actually a real issue or not.

**Comment by codefromthecrypt** [comment]
looks like @mathetake's eagle eyes saved the day!
