### ISSUE TITLE
Consider adding a stubbing API

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#810]
**Is your feature request related to a problem? Please describe.**
Right now, built-in host imports like emscripten are allowed to stub calls such that no host call is made. This is done via writing wasm instructions to return a constant (or no value on nullary).

Stubbing unused callbacks in wasm is more performant than calling a host function that does nothing, and also removes error conditions otherwise possible.

**Describe the solution you'd like**
I'm considering if we should add a stubbing version of `ModuleBuilder.ExportFunction`

**Describe alternatives you've considered**
Do nothing and let people wire up no-op functions. Possibly try to use reflection to see if a function is a no-op and stub automatically. I don't know if this is possible.

**Additional context**
I think we could cite some ABI that may end up having no-op callbacks, possibly proxy-wasm, and how many of those are in the critical path. maybe @anuraaga might know if this is worth doing routinely.

**Comment by anuraaga** [comment]
Personal experience is that I generally stub functions until a binary do finally loads, under the expectation that these aren't actually used in my actual use case. If they're actually used they'd generally need to actually be implemented, not just stubbed I guess.

What could be quite handy for me is not a stubbing API but an option to autostub missing imports, probably either as no-opish (ish being some coercion to zero value for results) and panic. I would often use that I think, and it wouldn't require any explicit stubbing while also providing information to then implement the functions that are actually used at runtime.

This comes from the learning that it's very easy for a compiler to end up adding host imports just because the code exists even when not used in the final binary. For Envoy where I don't control the host I have even rewritten unused imports not available to unrelated functions with the same signature - autostubbing would definitely be better than that :D

**Comment by codefromthecrypt** [comment]
Interesting idea on auto-panic ;) That's helpful I suppose for some wasm that imports a great deal of things but not sure what's used. Would have been helpful in the past in WASI I think.

There are callbacks that aren't used, for example memory view refresh, logging when disabled etc. Probably, we can have some benchmarks to show that things like this (maybe not memory view refresh as that's uncommonly code), but certainly things like disabled loggers, or callbacks on certain lifecycle hooks where performance will suffer as crossing the host side is expensive especially only to do nothing. OTOH, it is likely that we can prove this instead of say it. I'll keep this open until the most likely candidates for it (ex proxy-wasm) we can see how often things are called. 

Meanwhile, I'll deprioritize this! Thanks for the feedback @anuraaga!

**Comment by codefromthecrypt** [comment]
I think stubbing isn't very needed now especially with the reduced performance cost of calling host functions.
