### ISSUE TITLE
WASI fd_pread incorrectly moves file offset

### ISSUE THREAD

**Issue by ncruces** [tetratelabs/wazero#958]
**Describe the bug**

The [`fd_pread`](https://github.com/WebAssembly/WASI/blob/snapshot-01/phases/snapshot/docs.md#-fd_preadfd-fd-iovs-iovec_array-offset-filesize---errno-size) WASI syscall incorrectly moves the file offset.

Implementation probably can't be shared with `fd_read`, and should use `io.ReaderAt` not `io.ReadSeeker`.
https://github.com/tetratelabs/wazero/blob/6b9d119a7b069561ccb7f536a6d0d97d3772f549/imports/wasi_snapshot_preview1/fs.go#L561-L624

**To Reproduce**

```sh
git clone https://github.com/ncruces/wazero-bugs.git
cd wazero-bugs

echo Expected output:
cc -o main main.c && ./main

echo Actual output:
go run ./cmd
```

**Expected behavior**

```
Expected output:
Line 1
Line 2
Line 1
Line 3
Actual output:
Line 1
Line 2
Line 1
Line 2
```

Note the difference in the last line.

**Environment (please complete the relevant information):**
- Go version: 1.19.4
- wazero Version: v1.0.0-pre.5
- Host architecture: amd64
- Runtime mode: compiler

**Additional context**

[`main.c`](https://github.com/ncruces/wazero-bugs/blob/main/main.c) and [`main.go`](https://github.com/ncruces/wazero-bugs/blob/main/cmd/main.go) should be pretty self explanatory.
`main.wasm` from the repo was compiled with `zig cc --target=wasm32-wasi` version `0.10.0`.

I tried running it with `wasmtime --dir . main.wasm` which produces the correct output.

**Comment by ncruces** [comment]
I can try and fix this maybe next week if I can spare the time.
Happy holidays!

**Comment by codefromthecrypt** [comment]
thanks, would be great to have a hand!

**Comment by ncruces** [comment]
Sure. The implementation should be straight forward. But I wonder about tests. Do I submit a wasm file as test data? Do we build one from source? Do you have a preferred language/toolchain for this?

**Comment by codefromthecrypt** [comment]
@ncruces thanks for following along.

ps. the only other main thing we do is vet against other implementations because correct is more a quorum than a fact in wasi. It looks like you already checked with wasmtime and clang (wasi-libc). since the people who define what wasi is maintain those two things, I'd say quorum satisfied. TL;DR; is tests are the main thing once we're sure what the impl should be, and you already vetted that.

**Comment by codefromthecrypt** [comment]
ps for the tests, I think you can add one to wasi_stdlib_test.go because it is stateful so a bit harder to reproduce naturally in normal unit tests. Mainly, we want to make sure someone doesn't "fix" the implementation and break what you needed (as others will need it too)

I'm also investigating [wasi-testsuite](https://github.com/WebAssembly/wasi-testsuite) but I'm not sure if that covers this case or not. The goal is to eventually run wasi-testsuite like we do for core spectests.

**Comment by ncruces** [comment]
No longer needed for `go:embed` (from 1.21):
https://github.com/golang/go/issues/57803#event-8989467802
