### ISSUE TITLE
Grammatical errors in public API

### ISSUE THREAD

**Issue by lthibault** [tetratelabs/wazero#995]
My technical knowledge of WASM is limited, so my contributions are in turn limited to flagging grammatical errors in the public API.  I hope this is helpful! 🙂 

As I was glancing over the API documentation, I noticed the `ImportedMemories` and `ExportedMemories` methods on the `CompiledModule` interface.  In English, the "countable" plural _memories_ is used to talk about episodic memory (_e.g._ childhood memories), whereas the "uncountable" plural _memory_ can refer to a storage medium.  Thus, symbol names such as `ImportedMemory` and `ExportedMemory` seem more appropriate to me.  If we want to emphasize the fact that there are several discrete memory segments being imported/exported, I would suggest the names `MemoryImports` and `MemoryExports` instead.

Obviously, this is not a critical issue, but I thought I would bring it up anyway.  If this feedback is helpful, I would be happy to review the rest of the documentation and submit PRs to improve the docs.  Let me know!

**Comment by lthibault** [comment]
Strange, [the specs](https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#memories%E2%91%A2) occasionally refer to memory segments as _memories_.    I'm still in favor of renaming, but again, this isn't a critical issue.

**Comment by codefromthecrypt** [comment]
We had a conflict on name with api.Module where we ended up naming ExportedMemoryDefinitions because if we said ExportedMemories (for definitions which is what CompiledModule returns), it would have clashed conceptually with ExportedMemory which returns a different result (instance vs definition). We would have a similar naming issue with MemoryExports. 

I think it is worth changing CompiledModule to match what api.Module returns ExportedMemories -> ExportedMemoryDefinitions even if it is longer, as it is both more consistent and avoids the grammar glitch noted here. The end user impact will be low as these are niche functions. To rename in general things to Export/Import prefix would be more breaking iotw.

@mathetake wdyt

**Comment by mathetake** [comment]
Sg
